title: Notes & Code
author:
  name: Mrityunjay Bhardwaj
  email: mrityunjaybhardwaj99@gmail.com
  website: https://mrityunjay.ml/
description: > # this means to ignore newlines until "show_excerpts:"
  Collection of Notes and Code on Books that found intresting..

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage
sub_url: "/Notes-and-Code"
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: https://twitter.com/mrityunjay_99
    github:  https://github.com/MrityunjayBhardwaj
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
minima:
  skin: classic

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:path/
  main:
    output: true
    permalink: /:path/

defaults:
  - values:
      noCode: false